### ISSUE TITLE
SDK build currently broken

### ISSUE THREAD

**Issue by Ivan-Velickovic** [BreakawayConsulting/sel4cp#22]
It seems that 457a83fc0803fbe44fb445a5b1dc81bd3461beef causes the SDK to no longer build. Attempting to build the SDK will give the following error when it tries to build the kernel for the i.MX8MM-EVK:

```
CMake Error at build/imx8mm/release/sel4/build/cmake_install.cmake:46 (file):
  file INSTALL cannot duplicate symlink
  "/sel4cp/seL4/libsel4/sel4_plat_include/imx8mm-evk"
  at
  "/sel4cp/build/imx8mm/release/sel4/install/libsel4/include":
  File exists.
```

I believe this is fixed with https://github.com/seL4/seL4/pull/629. Not sure whether this commit to seL4 should be cherry-picked or should update the kernel to mainline?

I think this also shows some basic CI that runs on each PR that simply attempts to build the SDK would be nice...

**Comment by lsf37** [comment]
> I think this also shows some basic CI that runs on each PR that simply attempts to build the SDK would be nice...

That'd be great and will be required for the move to foundation repos in any case. If you're building CI, it'd be good to use the infrastructure in [seL4/ci-actions ](https://github.com/seL4/ci-actions/) so we don't introduce yet another way to do CI.

Happy to help if there are questions or specific things that need doing.

**Comment by Ivan-Velickovic** [comment]
I already have it working on my fork, just need to adjust it a bit.

**Comment by Ivan-Velickovic** [comment]
I've opened a PR that adds basic CI here: https://github.com/BreakawayConsulting/sel4cp/pull/24. In the interest of simplicity and getting something working I have not yet integrated it with the seL4 CI way of doing things.

**Comment by Ivan-Velickovic** [comment]
Temporarily resolved in https://github.com/BreakawayConsulting/sel4cp/pull/34, see the PR for details.
