### ISSUE TITLE
build_sdk.py fails to build monitor

### ISSUE THREAD

**Issue by malus-brandywine** [BreakawayConsulting/sel4cp#5]
After making all the upgrades mentioned in build instructions [build instructions](https://github.com/BreakawayConsulting/sel4cp/blob/main/README.md#developer-system-requirements) build_sdk.py still fails to build monitor.
The reason is that cmake doesn't install required sel4 headers and kernel.elf  to where they are expected to be.

The issue was observed while running the script in updated Docker container [submitted recently](https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles/pull/42)

Do you have updated an build_sdk.py script? kernel scripts?

**Comment by bennoleslie** [comment]
Thanks for trying it out.

Can you please provide the output you received to assist in resolving the
issue.

Thanks!

**Comment by malus-brandywine** [comment]
Resolved in #13
